module.exports = {
	SERVICES_CREDENTIALS: 'credentials',
	STEAM: 'steam',
	TWITCH: 'twitch',
	KARDS: 'kards',
	MONGODB: 'MongoDB',
	TENANT_ID: 'tenantId',
	CLIENT_ID: 'clientId',
	API_KEY: 'apikey',
	SECRET: 'secret',
	USERNAME: 'username',
	PASSWORD: 'password',
	URL: 'url',
	OAUTH_SERVER_URL: 'oauthServerUrl',
	REDIRECT_URI: 'redirectUri',
	PREFERRED_LOCALE: 'preferredLocale',
	SERVICE_VERSION: 'version',
	STEAM_STRATEGY_NAME: 'steam',
	GENERIC_ERROR: 'Error occurred making request'
};
